# Generated by Django 3.1.7 on 2023-07-28 17:14

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', account.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Tech', 'TECH'), ('Admin', 'ADMIN'), ('Staff', 'STAFF')], default='Staff', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Inactive', 'INACTIVE'), ('Active', 'ACTIVE'), ('Blocked', 'BLOCKED')], default='Inactive', max_length=15),
        ),
        migrations.AlterField(
            model_name='role',
            name='accesses',
            field=models.ManyToManyField(blank=True, related_name='access_roles', to='account.Access'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='role_users', to='account.Role'),
        ),
    ]
