# Generated by Django 3.1.7 on 2023-10-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230827_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Tech', 'TECH'), ('Admin', 'ADMIN'), ('Staff', 'STAFF'), ('Default', 'DEFAULT')], default='Default', max_length=15),
        ),
    ]
