FROM python:3.9
LABEL NAME="booking backend api version 1"

ENV PYTHONUNBUFFERED 1

RUN apt-get update -y
RUN apt-get install libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0 -y


RUN mkdir /api
WORKDIR /api

ADD requirements.txt /api
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /api
# RUN pipenv install --system

CMD ["gunicorn", "--bind", ":5050", "config.wsgi:application", "--timeout", "60"]