version: "3.8"

services:
  booking_psql:
    image: postgres:15
    container_name: booking_psql
    restart: always
    env_file: .env
    ports:
      - 5434:5432
    networks:
      - booking_apiv1_network

    volumes:
      - booking_apiv1_psql:/var/lib/postgresql/data


  booking_mongo:
    image: mongo
    container_name: booking_mongo
    restart: always
    env_file: .env
    ports:
      - 27018:27017
    networks:
      - booking_apiv1_network

    volumes:
      - booking_apiv1_mongo:/data/db


  booking_mongo_express:
    image: mongo-express
    container_name: booking_mongo_express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_INITDB_ROOT_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      ME_CONFIG_MONGODB_SERVER: booking_mongo
    ports:
      - 8081:8081/tcp

    networks:
      - booking_apiv1_network


  booking_redis:
    image: redis:7
    container_name: booking_redis
    restart: always
    env_file: .env
    networks:
      - booking_apiv1_network


  booking_apiv1:
    container_name: booking_apiv1
    build:
      context: .
      dockerfile: DockerFile
    restart: always
    depends_on:
      - booking_redis
      - booking_psql
      - booking_mongo

    networks:
      - booking_apiv1_network

    volumes:
      - ./:/api
      - booking_apiv1_static:/api/static
      - booking_apiv1_file:/api/file/upload

    command:
      [
        "gunicorn",
        "-w",
        "4",
        "--bind",
        ":5050",
        "config.wsgi:application"
      ]


  booking_celery_worker:
    container_name: booking_celery_worker
    build:
      context: .
      dockerfile: DockerFile
    restart: always
    depends_on:
      - booking_apiv1

    networks:
      - booking_apiv1_network

    volumes:
      - ./:/api

    command:
      [
        "celery",
        "-A",
        "common.celery",
        "worker",
        "--time-limit=300",
        "--concurrency=4",
        "--max-memory-per-child=40000",
      ]


  booking_nginx:
    container_name: booking_nginx
    build:
      context: .
      dockerfile: DockerFileNginx
    restart: always
    ports:
      - 5000:5000
    volumes:
      - booking_apiv1_static:/booking_apiv1/static
      - booking_apiv1_file:/booking_apiv1/file/upload

    networks:
      - booking_apiv1_network

    depends_on:
      - booking_apiv1

    command: [ nginx, "-g", "daemon off;" ]


volumes:
  booking_apiv1_static:
  booking_apiv1_file:
  booking_apiv1_mongo:
    external: true
  booking_apiv1_psql:
    external: true

networks:
  booking_apiv1_network:
    external: true