# Generated by Django 3.1.7 on 2023-10-03 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('reference_id', models.TextField(max_length=32)),
                ('hotel_code', models.IntegerField()),
                ('hotel_name', models.TextField()),
                ('room_code', models.TextField()),
                ('room_description', models.TextField()),
                ('rate_key', models.TextField()),
                ('hotel_item_id', models.TextField()),
                ('car_code', models.TextField(blank=True, null=True)),
                ('car_name', models.TextField(blank=True, null=True)),
                ('search', models.JSONField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('hotel_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('car_amount', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('hotel_fee_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('car_fee_amount', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('status', models.CharField(choices=[('Initiate', 'INITIATE'), ('DONE', 'DONE')], default='Initiate', max_length=15)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('currency', models.TextField(blank=True, max_length=3, null=True)),
                ('payment_method', models.TextField(blank=True, max_length=10, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('payer', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('Initiate', 'INITIATE'), ('Paid', 'PAID'), ('Success', 'SUCCESS'), ('Failed', 'FAILED'), ('Cancelled', 'CANCELLED'), ('Refund', 'REFUND')], default='Initiate', max_length=15)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': ['-created_at'],
            },
        ),
    ]
