# Generated by Django 3.1.7 on 2023-10-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20231007_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='intent_client_secret',
            field=models.TextField(blank=True, null=True),
        ),
    ]
