# Generated by Django 3.1.7 on 2023-10-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20231012_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_car_amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_hotel_amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
