"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from corsheaders.defaults import default_headers


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG_DJANGO") == "True"

# Other ENVIRONMENT : TEST, PRODUCTION
ENVIRONMENT_APP = os.environ.get("ENVIRONMENTDEV", "DEVELOPE")

ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")

if ENVIRONMENT_APP == "DEVELOPE":
    ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    # 3rd Party Apps
    'rest_framework',
    'drf_yasg',
    'corsheaders',
    'django_filters',
    # apps
    'account.apps.AccountConfig',
    'file.apps.FileConfig',
    'common.apps.CommonConfig',
    'content.apps.ContentConfig',
    'hotel.apps.HotelConfig',
    'car.apps.CarConfig'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'config.exceptions.ExceptionMiddleware'
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'static')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# Postgres
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get("POSTGRES_DB"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "HOST": os.environ.get("POSTGRES_HOST"),
        "PORT": int(os.environ.get("POSTGRES_PORT")),
    }
}

MONGO_DB_SETTING = {
    'NAME': os.environ.get("MONGODB_DATABASES_DATABASE_NAME"),
    'CLIENT': {
        'host': os.environ.get("MONGODB_DATABASES_DATABASE_HOST"),
        'port': int(os.environ.get("MONGODB_DATABASES_DATABASE_PORT")),
        'username': os.environ.get("MONGO_INITDB_ROOT_USERNAME"),
        'password': os.environ.get("MONGO_INITDB_ROOT_PASSWORD"),
        'authMechanism': 'SCRAM-SHA-1'
    },
}
MONGO_SEARCH_CACHE = int(os.environ.get("MONGO_SEARCH_CACHE", 24))

# Mongo
# MONGO_DB_SETTING = {
#     'NAME': os.environ.get("MONGODB_DATABASES_DATABASE_NAME"),
#     'CLIENT': {
#         'host': os.environ.get("MONGODB_DATABASES_DATABASE_HOST"),
#         'port': int(os.environ.get("MONGODB_DATABASES_DATABASE_PORT")),
#         'username': os.environ.get("MONGO_INITDB_ROOT_USERNAME"),
#         'password': os.environ.get("MONGO_INITDB_ROOT_PASSWORD"),
#         'authMechanism': 'SCRAM-SHA-1'
#     },
# }

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ["email", "first_name", "last_name"],
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {'NAME': 'account.validators.UppercaseValidator', },
    {'NAME': 'account.validators.NumberValidator', },
    {'NAME': 'account.validators.LowercaseValidator', },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/


TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# User Default Model
AUTH_USER_MODEL = "account.User"

# Settings of REST_FRAMEWORK

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'account.authentication.CustomizeTokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        # 'rest_framework.renderers.JSONRenderer',
        'config.renderers.ApiRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 500,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}

# Expire Token Config
TOKEN_AUTH_EXPIRED_TIME = os.environ.get(
    "TOKEN_AUTH_EXPIRED_TIME")  # second
if TOKEN_AUTH_EXPIRED_TIME:
    TOKEN_AUTH_EXPIRED_TIME = int(TOKEN_AUTH_EXPIRED_TIME)
else:
    TOKEN_AUTH_EXPIRED_TIME = 3*24*60*60  # 3 Days
EXPIRE_TOKEN_WHEN_USER_ACTIVE = os.environ.get(
    "EXPIRE_TOKEN_WHEN_USER_ACTIVE", "False") == "True"  # user token expire after 3 days
TIME_ACTIVE_OTP_SECONDS = 60*2  # 2 Minutes

# Swagger Config

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Token': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }
}

# logging config

LOGGING = {
    "disable_existing_loggers": False,
    "version": 1,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'celery': {
            'format': '{levelname} {asctime} {name} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'request': {
            'format': '{levelname} {asctime} {name} {absolute_url} {user} {ip} {request_data} {response_data} {duration} {start_time} {end_time} {query_count} {method} {status_code}',
            'style': '{',
        },
        'json': {
            'class': 'config.logger.CustomJsonFormatter'
        },
    },
    'handlers': {
        'streamer': {
            'class': 'logging.StreamHandler',
        },
        'project': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs/project.log',
            'maxBytes': 50000000,
            'backupCount': 5,
            'formatter': 'json',
            'level': 'INFO',
        },
        'celery': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs/celery.log',
            'maxBytes': 50000000,
            'backupCount': 5,
            'formatter': 'json',
            'level': 'INFO',
        },
        'testlogger': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs/test.log',
            'maxBytes': 50000000,
            'backupCount': 5,
            'formatter': 'json',
            'level': 'INFO',
        },
    },
    'root': {
        'handlers': ['streamer'],
        'level': 'INFO',
    },
    'loggers': {
        'project': {
            'handlers': ['project'],
            'level': 'INFO'
        },
        'project.testlogger': {
            'handlers': ['testlogger'],
            'level': 'INFO'
        },
        'django': {
            'handlers': ['streamer'],
            'level': 'INFO',
            'propagate': False,
        },
        'asyncio': {
            'handlers': ['streamer'],
            'level': 'INFO'
        },
        'celery': {
            'handlers': ['celery'],
            'level': 'INFO'
        },
    }
}

DATABASE_ROUTERS = ['config.db_routers.DBRouter']

# CORS
CORS_ORIGIN_WHITELIST = os.environ.get(
    "CORS_ORIGIN_WHITELIST", "http://localhost:3000").split(",")

CORS_ORIGIN_WHITELIST = [*CORS_ORIGIN_WHITELIST,
                         'http://localhost:3000',
                         'http://localhost:5000',
                         'http://127.0.0.1:3000'
                         ]

CORS_ALLOW_HEADERS = list(default_headers) + [
    'front-version',
]

# CACHE CONFIG
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_CACHE_LOCATION", "redis://127.0.0.1:6379/3"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 3,  # seconds
            "SOCKET_TIMEOUT": 3,  # seconds
            "IGNORE_EXCEPTIONS": True,
        },
    },
}

STATIC_ROOT = BASE_DIR / 'static'
STATIC_URL = '/static/'

FILES_PATH = BASE_DIR / 'file' / 'upload' if os.environ.get(
    "FILE_DIR", "/api/file/upload") == 'BASE_DIR' else Path("/api/file/upload")

RATELIMIT_ENABLE = os.environ.get("RATELIMIT_ENABLE", True) != "False"

BACKEND_URL = os.environ.get("BACKEND_URL_ADDRESS", "http://localhost:5000")

FRONT_BASE_URL = os.environ.get("FRONT_BASE_URL", "http://localhost:3000")

RESET_PASSWORD_URL = os.environ.get("RESET_PASSWORD_URL", "reset-password")
EMAIL_VERIFICATION_URL = os.environ.get(
    "EMAIL_VERIFICATION_URL", "auth/register/activation")

DATA_UPLOAD_MAX_MEMORY_SIZE = 1024*1024*7

# full part of upload dir in api responses before the name of file and other sub dirs
FILES_DOWNLOAD_BASE_URL = os.environ.get(
    "FILES_DOWNLOAD_BASE_URL", "http://localhost:5000/api/file/upload")

# notify settings
LIMIT_EMAIL_PER_MINUTE = 3
LIMIT_SMS_PER_MINUTE = 3

EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', ''))
EMAIL_USERNAME = os.environ.get('EMAIL_USERNAME', '')
EMAIL_PASSWORD = os.environ.get('EMAIL_PASSWORD', '')
EMAIL_SENDER = os.environ.get('EMAIL_SENDER', 'Booking Platform')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

LIMIT_UPLOAD_PER_HOUR_BYTES = 104857600  # 1024*1024*100 -> 100 MB
LIMIT_UPLOAD_PER_DAY_BYTES = 524288000  # 1024*1024*500 -> 500 MB

CELERY_BROKER_URL = os.environ.get(
    'CELERY_BROKER_URL', 'redis://localhost:6379')
CELERY_RESULT_BACKEND = os.environ.get(
    'CELERY_RESULT_BACKEND', 'redis://localhost:6379')
CELERY_INSPECT_TIMEOUT = int(os.environ.get('CELERY_INSPECT_TIMEOUT', '1'))

# TWILIO SMS CONFIGS
SMS_API_ACCOUNT_SID = os.environ.get('SMS_API_ACCOUNT_SID', "")
SMS_API_AUTH_TOKEN = os.environ.get('SMS_API_AUTH_TOKEN', "")
SMS_API_USER = os.environ.get('SMS_API_USER', "")
SMS_API_PASS = os.environ.get('SMS_API_PASS', "")
SMS_API_SENDER = os.environ.get('SMS_API_SENDER', "")  # "+15017250604"

# Hotelbeds info
HOTELBEDS_BASE_URL = os.environ.get(
    "HOTELBEDS_BASE_URL", "https://api.test.hotelbeds.com")
HOTELBEDS_API_KEY = os.environ.get(
    "HOTELBEDS_API_KEY", "70ee9c04c862f43c76bec6dff2e6a265")
HOTELBEDS_SECRET = os.environ.get("HOTELBEDS_SECRET", "e8be986f34")

# Stripe Payment Gateway
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY")
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY")
STRIPE_BASE_URL = os.environ.get("STRIPE_BASE_URL")

REDIS_HOST = os.environ.get('REDIS_HOST', 'booking_redis')
REDIS_PORT = int(os.environ.get('REDIS_PORT', '6379'))

HOTEL_FEE_PERCENTAGE = int(os.environ.get('HOTEL_FEE_PERCENTAGE', 0))
CAR_FEE_PERCENTAGE = int(os.environ.get('CAR_FEE_PERCENTAGE', 0))
